[package]
name = "ferrimon-common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
csv.workspace = true
chrono = { workspace = true, features = ["serde"] }
tracing.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util.workspace = true
thiserror.workspace = true
